AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SSR Generator Lambda Function - Bulk Generation Version

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024

Resources:
  SSRGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ssr-generator
      CodeUri: .
      Handler: dist/index.handler
      Runtime: nodejs20.x
      Description: Generates Safety Status Reports (Bulk Generation - 1 Claude API call)
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          OPENAI_API_KEY: !Ref OpenAIApiKey
          PINECONE_API_KEY: !Ref PineconeApiKey
          PINECONE_INDEX_NAME: !Ref PineconeIndexName
          S3_BUCKET_NAME: !Ref S3BucketName
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName

Parameters:
  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: Anthropic API Key
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key for embeddings
  PineconeApiKey:
    Type: String
    NoEcho: true
    Description: Pinecone API Key
  PineconeIndexName:
    Type: String
    Default: safety-status-report-tool
    Description: Pinecone Index Name
  S3BucketName:
    Type: String
    Default: safety-status-report-tool
    Description: S3 Bucket Name for file storage

Outputs:
  SSRGeneratorFunctionArn:
    Description: SSR Generator Lambda Function ARN
    Value: !GetAtt SSRGeneratorFunction.Arn
  SSRGeneratorFunctionName:
    Description: SSR Generator Lambda Function Name
    Value: !Ref SSRGeneratorFunction